project:
  type: website
  output-dir: docs

website:
  title: "Ben's Website"
  navbar:
    left:
      - href: index.qmd
        text: About me
      - href: resume.qmd
        text: Resume
      - href: projects.qmd
        text: Projects
      - href: fantasy-championship.qmd
        text: 🏆 Fantasy Basketball

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
